name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: miniderm

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install semantic-release
      run: npm install semantic-release@latest

    - name: Run semantic-release
      id: semantic
      run: npx semantic-release --dry-run=false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.semantic.outputs.new_release_version }}
        file: ./Dockerfile

    - name: Update the version in the project
      run: |
        # Logic to update the version in your .NET project files
        echo "New version is: ${{ steps.semantic.outputs.new_release_version }}"
