name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: miniderm

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install semantic-release
      run: npm install semantic-release@latest

    - name: Run semantic-release and capture version
      run: |
        OUTPUT=$(npx semantic-release --dry-run=false)
        NEW_VERSION=$(echo "$OUTPUT" | grep -o 'Published release [0-9.]*' | awk '{print $3}')
        echo "New version is $NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Make Repo Owner name case-safe
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_TOKEN }}
        
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.NEW_VERSION }}
        file: ./Dockerfile

    - name: Update the version in the project
      run: |
        echo "New version is now: ${{ env.NEW_VERSION }}"
