name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Semantic Version
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 17
        branches: main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Get the version
      run: echo "RELEASE_VERSION=$(cat ./VERSION)" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
